### ISSUE TITLE
 stability of holograms 

### ISSUE THREAD

**Issue by wdear** [jldailey13/HoloBlocks#1]
Hi~　
I focus on reducing offset of holograms these days, and found that stability of holograms in this project satisfied my expectation.  In my own apps, as well as _Holograms_ APP in Hololens, holograms have offset in centimeters when I move my head. But in this project they remain in position with little shaking.
I looked through in Unity and wondered if you have use Anchor or anything special to achive stability, only found Spatial Mapping may matters here.
Have you ever considered stability  in this development? if did, suggestions on it is appreciate.
Thanks!

**Comment by jlkorth** [comment]
Hello,
We are glad you are satisfied with our HoloBlocks app!  When developing, I don't believe we considered stability of the holograms too much.  We mostly based our gravity/physics implementation and spatial mapping (for surface detection) on the Holograms 101 Tutorial released by Microsoft.  You probably have already seen the Holograms 101 Tutorial, but I will paste the link here in case other people are interested: https://developer.microsoft.com/en-us/windows/mixed-reality/holograms_101

Sorry we could not be of more help, and thank you for trying our app!
- Team HoloCare
